const lazy = [
    "apathetic",
    "careless",
    "dull",
    "inattentive",
    "indifferent",
    "lackadaisical",
    "lethargic",
    "passive",
    "sleepy",
    "tired",
    "weary",
    "asleep-on-the-job",
    "comatose",
    "dallying",
    "dilatory",
    "drowsy",
    "flagging",
    "idle",
    "indolent",
    "inert",
    "laggard",
    "lagging",
    "languid",
    "languorous",
    "lifeless",
    "loafing",
    "neglectful",
    "out-of-it",
    "procrastinating",
    "remiss",
    "shiftless",
    "slack",
    "slothful",
    "slow",
    "slow-moving",
    "snoozy",
    "somnolent",
    "supine",
    "tardy",
    "torpid",
    "trifling",
    "unconcerned",
    "unenergetic",
    "unindustrious",
    "unpersevering",
    "unready",
];

export const getLazy = () =>
    Math.random() > 0.33
        ? "lazy"
        : lazy[Math.floor(Math.random() * lazy.length)];
