export const optimism = [
    "You are successful.",
    "You are confident.",
    "You are powerful.",
    "You are strong.",
    "You are getting better and better every day.",
    "All You need is within you right now.",
    "You wake up motivated.",
    "You are an unstoppable force of nature.",
    "You are a living, breathing example of motivation.",
    "You are living with abundance.",
    "You are having a positive and inspiring impact on the people You come into contact with.",
    "You are inspiring people through your work.",
    "You're rising above the thoughts that are trying to make you angry or afraid.",
    "Today is a phenomenal day.",
    "You are turning DOWN the volume of negativity in your life, while simultaneously turning UP the volume of positivity.",
    "You are filled with focus.",
    "You are not pushed by your problems; You are led by your dreams.",
    "You are grateful for everything you have in your life.",
    "You are independent and self-sufficient.",
    "You can be whatever you want to be.",
    "You are not defined your by past; You are driven by your future.",
    "You use obstacles to motivate you to learn and grow.",
    "Today will be a productive day.",
    "You are intelligent and focused.",
    "You feel more grateful each day.",
    "You are getting healthier every day.",
    "Each and every day, you are getting closer to achieving your goals.",
    "Through the power of your thoughts and words, incredible transformations are happening in you and within your life right now.",
    "You are constantly growing and evolving into a better person.",
    "You're freeing yourself from all destructive doubt and fear.",
    "You accept yourself for who you are and create peace, power and confidence of mind and of heart.",
    "You are going to forgive yourself and free yourself. You deserve to forgive and be forgiven.",
    "You are healing and strengthening every day.",
    "You've made it through hard times before, and you've come out stronger and better because of them. You're going to make it through this.",
    "You do not waste away a single day of your life. You squeeze every ounce of value out of each of your days on this planet—today, tomorrow, and everyday.",
    "You must remember the incredible power you possess within you to achieve anything you desire.",
    "You do not engage with people who try to penetrate your mind with unhelpful thoughts and ideas—You walk away when a person or a situation isn’t healthy for you.",
    "You belong in this world; there are people that care about you and your worth.",
    "Your past might be ugly, but you are still beautiful.",
    "You have made mistakes, but you will not let them define you.",
    "Your soul radiates from the inside and warms the souls of others.",
    "You don't compare yourself to others. The only person You compare yourself to is the person you were yesterday. And as long as the person You are today is even the tiniest bit better than the person you were yesterday—You're meeting your own definition of success.",
    "Note to self: You are going to make you so proud.",
    "You finish what matters and let go of what does not.",
    "You feed your spirit. You train your body. You focus your mind. This is your time.",
    "Your life has meaning. What you do has meaning. Your actions are meaningful and inspiring.",
    "What you have done today was the best you were able to do today. And for that, you are thankful.",
    "One small positive thought in the morning can change your whole day. So, today you rise with a powerful thought to set the tone and allow success to reverberate through every moment of your day.",
    "You set goals and go after them with all the determination you can muster. When you do this, your own skills and talents will take you to places that amaze you.",
    "Happiness is a choice, and today You choose to be happy.",
];

export const getOptimism = () =>
    optimism[Math.floor(Math.random() * optimism.length)];
